nohup: ignoring input
Traceback (most recent call last):
  File "/home/QQbot/robot.py", line 5, in <module>
    import qqbot
ModuleNotFoundError: No module named 'qqbot'
2024-11-05 11:26:27,338 - INFO - 机器人启动中...
2024-11-05 11:26:27,593 - INFO - [连接管理]程序启动...
2024-11-05 11:26:27,596 - INFO - [连接池]最大并发连接数: 1, 启动会话数: 1
2024-11-05 11:26:27,596 - INFO - [连接管理]新会话启动中...
2024-11-05 11:26:27,597 - INFO - [ws连接]启动中...
2024-11-05 11:26:27,726 - INFO - [ws连接]鉴权中...
2024-11-05 11:26:27,728 - INFO - [ws连接]心跳检测启动...
2024-11-05 11:26:27,838 - INFO - [ws连接]鉴权成功
2024-11-05 11:26:27,839 - INFO - [ws连接]程序启动成功！
2024-11-05 11:27:01,993 - INFO - 收到消息：/天气 上海
2024-11-05 11:27:02,205 - INFO - 回复天气请求：上海的天气是：多云，温度为 18 °C
2024-11-05 11:27:13,041 - INFO - 收到消息：/运行状态
2024-11-05 11:27:14,052 - INFO - 回复运行状态请求
2024-11-05 11:42:09,179 - INFO - 收到消息：/运行状态
2024-11-05 11:42:10,182 - INFO - 回复运行状态请求
2024-11-05 11:44:41,454 - INFO - [连接管理]服务强行停止!
2024-11-05 11:44:41,454 - INFO - 程序被手动终止。
2024-11-05 11:44:45,044 - INFO - 机器人启动中...
2024-11-05 11:44:45,291 - INFO - [连接管理]程序启动...
2024-11-05 11:44:45,291 - INFO - [连接池]最大并发连接数: 1, 启动会话数: 1
2024-11-05 11:44:45,291 - INFO - [连接管理]新会话启动中...
2024-11-05 11:44:45,291 - INFO - [ws连接]启动中...
2024-11-05 11:44:45,426 - INFO - [ws连接]鉴权中...
2024-11-05 11:44:45,426 - INFO - [ws连接]心跳检测启动...
2024-11-05 11:44:45,531 - INFO - [ws连接]鉴权成功
2024-11-05 11:44:45,531 - INFO - [ws连接]程序启动成功！
2024-11-05 11:49:51,776 - INFO - 收到消息：/运行状态
2024-11-05 11:49:52,787 - INFO - 回复运行状态请求
